// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDJ0ST6ExGE26hJwCzx5w7e8YsdQK-IU0',
    appId: '1:119777655876:web:1ea2be0d9ead8ce3dd5011',
    messagingSenderId: '119777655876',
    projectId: 'uniqtech-crm-321fc',
    authDomain: 'uniqtech-crm-321fc.firebaseapp.com',
    storageBucket: 'uniqtech-crm-321fc.firebasestorage.app',
    measurementId: 'G-JLFDSE9TQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU8dCZwlfTwkQS8zUJx0TcNs9q06iaFvY',
    appId: '1:119777655876:android:171a78fb007ff24cdd5011',
    messagingSenderId: '119777655876',
    projectId: 'uniqtech-crm-321fc',
    storageBucket: 'uniqtech-crm-321fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIxKoUYIjbuUveN2hzWMbSBFnenxrCQy0',
    appId: '1:119777655876:ios:5b68ea137f1e33c9dd5011',
    messagingSenderId: '119777655876',
    projectId: 'uniqtech-crm-321fc',
    storageBucket: 'uniqtech-crm-321fc.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

}