// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzDYBONq3rs1W-H9wBDfBExYE1P1MzcI',
    appId: '1:120903826359:web:c45381b80dcab64b354632',
    messagingSenderId: '120903826359',
    projectId: 'uniqtech-crm',
    authDomain: 'uniqtech-crm.firebaseapp.com',
    storageBucket: 'uniqtech-crm.firebasestorage.app',
    measurementId: 'G-2L11X8HTDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANBjvfAnS0XSZGZ-qbVTCU0ZXFudALnl4',
    appId: '1:120903826359:android:97cc8a10be0e7eb5354632',
    messagingSenderId: '120903826359',
    projectId: 'uniqtech-crm',
    storageBucket: 'uniqtech-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbNmsD9RQNOEYWIQsD12JvhEr9wClmXWE',
    appId: '1:120903826359:ios:b8c5487db657a6c2354632',
    messagingSenderId: '120903826359',
    projectId: 'uniqtech-crm',
    storageBucket: 'uniqtech-crm.firebasestorage.app',
    iosClientId: '120903826359-qe64evivpidi06rlcm9dguc8mvmqg46g.apps.googleusercontent.com',
    iosBundleId: 'com.example.crm',
  );
}
